---
title: "YAML Parameters"
description: |
  Instructions for defining site-specific parameters needed for the main pipeline.
vignette: >
  %\VignetteIndexEntry{YAML Parameters}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
editor: source
---

WAVES uses a YAML file (`_waves.yml`) to define parameters needed for the main pipeline. For more information on what YAML is, reference `vignette("yaml-2-minute-intro", package = "yaml12")`. It is not a necessary read, but may help with troubleshooting if the pipeline is erroring at `lst_yaml`.

# Previous Step

Please make sure you have already ran the configuration pipeline as detailed in `vignette("instructions-config")` before proceeding.

# Keys

The `_waves.yml` file has 6 top-level keys. Below are descriptions and examples for each top-level key:

## study_timezone

A string scalar that corresponds to the timezone the study data was collected in. It should be a location in IANA "Olson" format. That is, in:

- "\[CONTINENT -or- OCEAN\]/\[CITY\]" format

- "Etc/GMT\[INVERSE OFFSET\]" format

- "UTC" or "GMT"

See either:

- The output from running `Sys.timezone()` within the R Console to see the timezone of your computer system in Olson format, which you can use if you are in the same timezone that the data was collected in. Or...

- Reference "TZ identifier" column in the [tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) to find the the correct timezone. Prefer to use the rows that are highlighted green.

| Acceptable                     | Unacceptable   |
|--------------------------------|----------------|
| America/Chicago, Etc/GMT+6     | CST            |
| America/New_York, Etc/GMT+5    | EDT            |
| America/Los_Angeles, Etc/GMT+8 | PST            |
| Asia/Hong_Kong                 | Asia/Hong Kong |
| Asia/Katmandu                  | Katmandu       |
| Australia/Sydney               | NPT            |
| Europe/London                  | BST            |
| Europe/Paris                   | CET            |

## sampling_frequency

A integer scalar corresponding to the sampling frequency of the wrist activity monitors. If sampling_frequency changed during data collection, then a sequence of integers should be entered.

| Acceptable | Unacceptable |
|------------|--------------|
| 100        | 100Hz        |
| 30         | 29.9         |

## metadata_filepath

Filepath to csv file containing metadata for each participant, as described in [Metadata Codebook](articles/reference-codebook.html#metadata)

## deidentify

Boolean where depending on the value:

- `TRUE`: Pipeline will create a WAVES-specific ID for each participant listed within the metadata file specified by `metadata_filepath`.

  - The WAVES-specific ID for each participant is needed in order for the merged output to be shared with the WAVES team.

  - Each site will have the "key" that links the participant's study ID's with WAVES-specific ID's, and ***will not*** be shared with the WAVES team.

  - As the WAVES-specific ID is generated every time a change to the `_waves.yml` file is made, it is only applied to:

    - merged output that will be shared to the WAVES team
    - summary reports showing which files made it through the pipeline.

- `FALSE`: Provided `study` and `subject` fields from metadata file will be used.

  - For the WAVES project, `deidentify` will never be set to `FALSE`.

  - This is more relevant for when WAVES repository will eventually be formatted as a package for submission to CRAN.

## site

2-3 letter identifier given to each site that will be used within the WAVES-specific ID. Usually an acronym of the university or lab where the study data is being held.

## wrist_accelerometer

Sequence of mappings that define where raw wrist accelerometer files are in your computer system. Only the `directories` key or `filepaths` key should be defined, not both.

## directories {#fdr}

One or more directories where the raw accelerometer files are being held. The directories should only hold raw files that are all the same extension (.gt3x, .cwa, .bin, .csv). Additionally, the directories:

- ***can*** hold sub-directories or files that do not end in .gt3x, .cwa, .bin or .csv.

- ***should not*** hold multiple formats of the same recording/session

  - For example, if MYFILE_001.gt3x is in the directory, there should not be a MYFILE_001.csv (raw csv export from ActiLife) in the directory as well.

- ***should not*** hold raw files from monitors not worn at the wrist

If the directory contains multiple formats of the same recording/session or contains raw files from different wear locations, then the `filepaths` key should be defined instead.

## filepaths

One or more filepaths that point directly to the raw files. Users will most likely define the filepaths by using the `!expr` tag to directly use R code. See the [values as an Expression section](#expr) for more information.

## reference

Sequence of mappings that define the reference measures being used and where they are located in your computer system.

## direct_observation

### filepath

Filepath that points directly to 3rd-person or 1st-person video-recorded direction observation labels formatted according to Reference Codebook [Direct Observation section](articles/reference-codebook.html$ref-do) in `.csv` format.

## still_image

### filepath

Filepath that points directly to 1st-person still-image labels formatted according to Reference Codebook [Wearable Camera section](articles/reference-codebook.html$ref-img) in `csv` format.

## activpal

See [Thigh-worn activPAL section](articles/reference-codebook.html#ref-ap) for guidance on exporting 1-second epoch files and EventsEx files from PAL Batch.

### 1secEpochs_directories

One or more directories where 1-second epoch activPAL files are located. The directories:

- ***can*** hold sub-directories or files that are neither 1-second or EventsEx files

- ***can*** be the same directory as where the EventsEx files are being held

- ***should not*** hold 1-second files exported with settings different than that specified within Reference Codebook [Thigh-worn activPAL section](articles/reference-codebook.html#ref-ap).

### 1secEpochs_filepaths

One or more filepaths that point directly to 1-second epoch activPAL files. Users will most likely define the filepaths by using the `!expr` tag to directly use R code. See the [Values as an Expression section](#expr) for more information.

### events_directories

One or more directories where 1-second epoch activPAL files are located. The directories:

- ***can*** hold sub-directories or files that are neither 1-second or EventsEx files

- ***can*** be the same directory as where the 1-second epoch files are being held

- ***should not*** hold EventsEx files exported with settings different than that specified within Reference Codebook [Thigh-worn activPAL section](articles/reference-codebook.html#ref-ap).

### events_filepaths

One or more filepaths that point directly to EventsEx activPAL files. Users will most likely define the filepaths by using the `!expr` tag to directly use R code. See the [Values as an Expression section](#expr) for more information.

### id_pattern

A string that represents the pattern in how activPAL files were named, particularly to identify the numeric identifier for each participant through zeroes. This option is necessary as, during initialization of an activPAL monitor, at most 7(?) characters. For example, the wrist accelerometer files may be named like so:

```
MYSTUDY_9999v1
```

and the activPAL files like so:

```
MS9999v1
```

in which case, `id_pattern` should be:

```
MS0000v1
```

where the zeroes are used to represent the unique numeric identifier of each participant. This will correspond with the `subject` field from the metadata.

## actipass

TODO

### directories

### filepaths

### id_pattern

# Values as an Expression {#expr}

YAML values can have a tag before defining a value, as noted in `vignette("yaml-tags-and-advanced-features", package = "yaml12")` . In WAVES, the `!expr` tag has been defined to evaluate text after the `!expr` tag as an R expression. For example, the following key: value pair

`my_number: !expr 6 * 7`

is equivalent to the following code in R

`list(my_number = 6 * 7)`

For any keys that have the word `filepaths`, it is recommended to use the `!expr` tag along with an R expression to easily define all filepaths instead of manually typing out every single filepath. This will typically be done using the `list.files()` function.

For example, if I wanted to list files that only had the `.csv.gz` extension within the WAVES repository, then the following would work in the YAML file:

```         
filepaths: !expr list.files(path = "data/0_CONFIG/RAW", pattern = "$\\.csv\\.gz", full.names = TRUE)
```

Note that the code is all kept on the same line, and the `full.names` argument is set to `TRUE`.

If you were to write `list.files()` across multiple lines, it would have to be written like so:

```         
filepaths:
  - !expr list.files(
      path = "data/0_CONFIG/RAW",
      pattern = "$\\.csv\\.gz",
      full.names = TRUE
    )
```

Note, in YAML language indentation matters, as it is essential for determining which sequences/mappings are within others. So the following would NOT work and return an error.

```         
filepaths:
  - !expr list.files(
  path = "data/0_CONFIG/RAW",
  pattern = "$\\.csv\\.gz",
  full.names = TRUE
)
```

This would happen if you were to copy and paste the R code directly from a script to the YAML file. If you do so, make sure to appropriately indent the code such that the `)` parenthesis is directly under the `!` in `!expr` tag.

# Next Step

Once the parameters in your YAML file have been entered, proceed to `vignette("instructions-main")` to run the main pipeline.

