---
title: "Reference Data Codebook"
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
description: >
  Description of variables required from some ground-truth data and variables from
  processing other ground-truth data.
vignette: >
  %\VignetteIndexEntry{Reference Codebook}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{quarto::html}
editor: source
---

Last Update: May 7, 2026

```{r}
cat("poop")
```


**Purpose**: Describe the variables for meta data and ground truth format for studies contributing data to the WAVES analysis. Designed to align with analysis plan below.

Of note, the expectation is for WAVES studies to map their existing labeled data to this codebook where possible. The expectation is not to relabel data for this analysis. In the excel appendix, studies should provide their labels, operational definitions and mappings.

## Analysis Plan - Aim 1 (primary reference video recorded DO)

Performance evaluation of three core metrics (sedentary time, step counting, moderate-vigorous physical activity) compared to a primary reference measure collected for a fixed amount of time, at least 1-hour hours within a free-living environment (i.e., naturalistic conditions, not laboratory or scripted).

Identify primary outcome of interest and propose a priori sensitivity analyses to examine accuracy across different domains and movement that are important for public health and/or may have a unique movement signal that should be considered.

1.  Sedentary TIme
    a)  **\*Total sedentary time**: Comparison of algorithms and ground-truth across all labeled data in final datasets.
    b)  **Broad domain**: Stratified by 5-class consistent with GPAQ where possible (household, occupation, travel, leisure, other)
    c)  **Sedentary types**: Stratified by 4-class: non-sedentary, sitting/reclining, lying, sedentary driving.
2.  Step Counting
    a)  **\*Total steps**: Comparison of algorithms and ground-truth across all labeled data in final datasets.
    b)  **Broad domain**: Stratified by 5-class consistent with GPAQ where possible (household, occupation, travel, leisure, other).
    c)  **Whole-body movement**: Stratified by 5-class (sedentary, mixed movement, walking, running, biking).
3.  Moderate-vigorous physical activity (MVPA)
    a)  **\*Total MVPA**: Comparison of algorithms and ground-truth across all labeled data in final datasets.
    b)  **Broad domain**: Stratified by 5-class consistent with GPAQ where possible (household, occupation, travel, leisure, other)
    c)  **Whole-body movement**: Stratified by 5-class (sedentary, mixed movement, walking, running, biking).

*\*Indicates primary analysis*

## Analysis Plan – Aim 2 (Day-level secondary comparisons)

Performance evaluation of three core metrics (sedentary time, step counting, MVPA) compared to a field-based secondary reference measure collected over one or more 24-hour periods in free-living conditions.

**Study Requirements**:

- Protocol that includes minimum of 16-hour wear protocol for wrist worn device and field-based reference measure.

- Simultaneous raw wrist-worn device AND a reference measure traceable to a primary reference method with acceptable accuracy and precision in field-based testing

## Metadata

Notes:

- • Variables indicated as **required** must be included for a study’s data to be used in this analysis.

### Data Dictionary

+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| variable | definition                                                                    | type                | levels  | specific labels/notes                        | missingness                            |
+==========+===============================================================================+=====================+=========+==============================================+========================================+
| site     | Study site identifier                                                         | character (nominal) | CP      | California Polytechnic State University      | none (required for each included file) |
|          |                                                                               |                     |         |                                              |                                        |
|          |                                                                               |                     | UWM     | University of Wisconsin-Milwaukee            |                                        |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| pid      | Unique participant identifier used to link observation data with device data. | alphanumeric        | \-      | Used to link with device and reference data. | none                                   |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| age      | Age of participant in years                                                   | numeric             | \-      | round to years                               | allowed (missing value = NA)           |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| bmi      | Participant’s BMI (kg/m2)                                                     | numeric             | \-      | \-                                           | allowed                                |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| gender   | Participant’s gender                                                          | character (nominal) | M       | Male                                         | allowed                                |
|          |                                                                               |                     |         |                                              |                                        |
|          |                                                                               |                     | F       | Female                                       |                                        |
|          |                                                                               |                     |         |                                              |                                        |
|          |                                                                               |                     | OTH     | Non-binary or any other categories           |                                        |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| device   | Wrist-worn device that was used in this study                                 | character (nominal) | AG3X    | ActiGraph GT3X+                              | none                                   |
|          |                                                                               |                     |         |                                              |                                        |
|          |                                                                               |                     | AXIV    | Axivity                                      |                                        |
|          |                                                                               |                     |         |                                              |                                        |
|          |                                                                               |                     | GA      | Geneactiv                                    |                                        |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| sampling | Sampling frequency of device in Hz                                            | numeric             | \-      | Value in Hz that data was set to sample      | none                                   |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+
| location | Wear location for device (non-dominant or dominant wrist)                     | character (nominal) | dom     | dominant                                     | none                                   |
|          |                                                                               |                     |         |                                              |                                        |
|          |                                                                               |                     | non_dom | non_dominant                                 |                                        |
+----------+-------------------------------------------------------------------------------+---------------------+---------+----------------------------------------------+----------------------------------------+

### Example

| site | pid   | age | bmi  | gender | device | sampling | location |
|------|-------|-----|------|--------|--------|----------|----------|
| CP   | CP001 | 21  | 23.4 | F      | AG3X   | 30       | non_dom  |

## [Primary Reference: Video-Recorded Direct Observation]{.underline}

Notes:

- Reference measure for sedentary time, step counts and MVPA.

- Row unit: one record per 1-second epoch of direct observation.

- Variables listed as required must be provided for the study’s data to be included in the analysis.

- The data provided to the team should be “clean” with all rows removed for observations that were non-codable/missing.

- intensity3_do and intensity4_do are MET-based classifications and should be internally consistent:

  - “mvpa” in intensity3_do corresponds to “moderate” or “vigorous” in intensity4_do.

- Sedtype_do provides a sedentary subtype classification and should align with:

  - posture_do = “sedentary”

  - intensity_do = “sedentary”

  - “non-sed” in Sedtype_do corresponds to all non-sedentary posture/intensity combinations.

- A study must have sedentary time, MVPA or steps labeled in a way consistent with operational definitions to be included in the analysis. The study does not need to have all three to be included, should provide NAs for metrics that aren’t labeled.

### Data Dictionary

::: {.list-table}
- - **variable**
  - definition
  - type
  - levels
  - labels/notes
  - missingness

- - []{rowspan=2} **site**
  - []{rowspan=2} Study site identifier
  - []{rowspan=2} character (nominal)
  - CP
  - California Polytechnic State University
  - []{rowspan=2} none (required for each included file)

- - UWM
  - University of Wisconsin–Milwaukee

- - **pid**
  - Unique participant identifier
  - alphanumeric
  - \- 
  - unique identifier variable that identifies participant and can be used to link with device data
  - none

- - **observation**
  - Observation session identifier
  - numeric (count)
  - \- 
  - If a participant is only observed once, then default to 1
  - none

- - **datetime**
  - Timestamp of observation in UTC timezone
  - POSIXct
  - \- 
  - Timestamp in coordinated universal time (UTC), YYYY-mm-dd HH:MM:SS format
  - none

- - **date**
  - Local calendar date at the observation site
  - date
  - \-
  - In year-month-day format (i.e. YYYY-MM-DD)
  - none
  
- - **time**
  - Local wall-clock time at the observation site
  - character
  - \-
  - In 24-hour hour:minute:second format (i.e. HH:MM:SS)
  - none
  
- - []{rowspan=5} **domain_do**
  - []{rowspan=5} Behavioral domain classification
  - []{rowspan=5} character (nominal)
  - leisure
  - Discretionary time activities including social activities, sports, fitness, recreation, and screen-based leisure activities
  - []{rowspan=5} allowed

- - household
  - Personal care, housework, lawn and garden work, exterior maintenance

- - transportation
  - Traveling to and from places (e.g., work, shopping, place of worship). Includes driving or riding in a car, public motorized transport (bus, train), and active transport

- - occupation
  - Work or school-related activities including paid or unpaid work, study, and seeking employment
  
- - other
  - Behaviors not categorized above (e.g., purchasing goods, volunteering, other uncategorized activities)

- - []{rowspan=5} **posture_do**
  - []{rowspan=5} Observed posture or movement type
  - []{rowspan=5} character (nominal)
  - sedentary
  - Sitting or lying
  - []{rowspan=5} allowed

- - mixed_movement
  - Includes standing, stand_move, sport_movement, stretching, crouching/kneeling/squatting, ascending/descending stairs

- - walking
  - L-R-L-R pattern including walking with load
  
- - running
  - Running
  
- - biking
  - Cycling

- - []{rowspan=4} **sedtype_do**
  - []{rowspan=4} Sedentary subtype classification
  - []{rowspan=4} character (nominal)
  - non_sed
  - All non-sedentary/active behaviors
  - []{rowspan=4} allowed

- - sitting
  - sitting/reclining not in a motor vehicle as a driver/passenger

- - lying
  - lying

- - vehicle
  - Driving a personal motor vehicle or as a passenger in any land-based motor vehicle
 
- - []{rowspan=3} intensity3_do
  - []{rowspan=3} 3-level intensity classification based on METs
  - []{rowspan=3} character (ordinal)
  - sedentary
  - sedentary posture with low energy expenditure
  - []{rowspan=3} allowed

- - light
  - non sedentary posture 1.50 - 2.99 METS

- - mvpa
  - 3.00+ METS
  
- - []{rowspan=4} intensity4_do
  - []{rowspan=4} 4-level intensity classification based on METs
  - []{rowspan=4} character (ordinal)
  - sedentary
  - sedentary posture with low energy expenditure
  - []{rowspan=4} allowed

- - light
  - non sedentary posture 1.50 - 2.99 METS

- - moderate
  - 3.00 -  5.99 METS
  
- - vigorous
  - 6.00+ METS
  
- - steps_do
  - Number of steps recorded during the 1-second epoch
  - count
  - \-
  - \-
  - allowed
:::

### Example

::: {.list-table}
- - site
  - pid
  - observation
  - datetime
  - date
  - time
  - domain_do
  - posture_do
  - sedtype_do
  - intensity3_do
  - intensity4_do
  - steps_do
  
- - CP
  - CP001
  - 1
  - 1990-01-01T18:36:10
  - 1990-01-01
  - 10:42:10
  - transportation
  - walking
  - non_sed
  - mvpa
  - moderate
  - 2
:::

## Thigh-worn device data dictionary
